"""Public API for the filesystem harness."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _metadata_version

from .core import Harness, HarnessConfig, HarnessError, HarnessResult, RunUsage, UnexpectedModelBehavior
from .hooks import (
    AfterSubagentRunContext,
    AfterToolCallContext,
    BeforeSubagentRunContext,
    BeforeToolCallContext,
    Hook,
    HookContext,
    HookEvent,
    HookRegistry,
    LimitReachedContext,
    RunEndContext,
    RunStartContext,
    UserPromptSubmitContext,
)
from .output import NativeOutput, OutputSchema, PromptedOutput, TextOutput, ToolStructuredOutput
from .providers import (
    AnthropicMessagesModel,
    AnthropicProvider,
    Model,
    ModelCapabilities,
    ModelNotice,
    ModelSession,
    ModelSettings,
    ModelToolCall,
    ModelTurn,
    OpenAIProvider,
    OpenAIResponsesModel,
    OpenRouterModel,
    OpenRouterProvider,
    Provider,
    StructuredOutputRequest,
    ToolOutput,
    infer_model,
    parse_model_ref,
)
from .subagents import DEFAULT_SUBAGENT_NAME, SubAgentArgs, SubAgentConfig, build_child_harness, create_subagent_tool
from .tools import (
    FilePromptSource,
    FileTools,
    InlinePromptSource,
    MCPDependencyError,
    MCPError,
    MCPServer,
    MCPServerSSE,
    MCPServerStdio,
    MCPServerStreamableHTTP,
    ModelRetry,
    ParallelLlmArgs,
    ParallelLlmTool,
    PathPolicy,
    PathValidationError,
    Skill,
    SkillRegistry,
    ToolResult,
    ToolSpec,
    builtin_tools,
    call_tool,
    contained_path,
    create_parallel_llm_tool,
)
from .tracing import LocalTracing, OtlpTracing, TracingOptions, create_local_tracing, create_local_tracing_options, create_otlp_tracing

try:
    __version__ = _metadata_version("thinharness")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    "__version__",
    "FileTools",
    "FilePromptSource",
    "InlinePromptSource",
    "Harness",
    "HarnessConfig",
    "HarnessError",
    "HarnessResult",
    "RunUsage",
    "ModelRetry",
    "UnexpectedModelBehavior",
    "MCPDependencyError",
    "MCPError",
    "MCPServer",
    "MCPServerSSE",
    "MCPServerStdio",
    "MCPServerStreamableHTTP",
    "AfterSubagentRunContext",
    "AfterToolCallContext",
    "BeforeSubagentRunContext",
    "BeforeToolCallContext",
    "Hook",
    "HookContext",
    "HookEvent",
    "HookRegistry",
    "LimitReachedContext",
    "RunEndContext",
    "RunStartContext",
    "UserPromptSubmitContext",
    "AnthropicMessagesModel",
    "AnthropicProvider",
    "Skill",
    "SkillRegistry",
    "SubAgentArgs",
    "SubAgentConfig",
    "DEFAULT_SUBAGENT_NAME",
    "Model",
    "ModelCapabilities",
    "ModelNotice",
    "ModelSettings",
    "ModelSession",
    "ModelToolCall",
    "ModelTurn",
    "OpenAIProvider",
    "OpenAIResponsesModel",
    "OpenRouterModel",
    "OpenRouterProvider",
    "Provider",
    "StructuredOutputRequest",
    "NativeOutput",
    "OutputSchema",
    "PromptedOutput",
    "TextOutput",
    "ToolStructuredOutput",
    "PathPolicy",
    "PathValidationError",
    "ParallelLlmArgs",
    "ParallelLlmTool",
    "ToolResult",
    "ToolSpec",
    "ToolOutput",
    "LocalTracing",
    "OtlpTracing",
    "TracingOptions",
    "build_child_harness",
    "builtin_tools",
    "call_tool",
    "contained_path",
    "create_parallel_llm_tool",
    "create_local_tracing",
    "create_local_tracing_options",
    "create_subagent_tool",
    "create_otlp_tracing",
    "infer_model",
    "parse_model_ref",
]
